### ISSUE TITLE
QAbstractDeclarativeObject.cpp compilation bug

### ISSUE THREAD

**Issue by tucnak** [KDAB/DeclarativeWidgets#1]
Just trying to build your library on Mac OS X:

```
git clone %path%
cd DeclarativeWidgets
qmake
make
```

and I got that build error:

```
abstractdeclarativeobject.cpp:65:37: error: no member named 'signature' in 'QMetaMethod'
      if (blacklist.contains(method.signature()))
                         ~~~~~~ ^
abstractdeclarativeobject.cpp:68:60: error: no member named 'signature' in 'QMetaMethod'
      const QByteArray signature = "2" + QByteArray(method.signature());
```

Environment is latest Mac OS X with Qt 5.1.0-RC1 from Qt Project and GNU make

**Comment by 0x6e** [comment]
Closing this ancient issue. DeclarativeWidgets should work with Qt 5.11 and above.
